# Generated by Django 4.0.1 on 2022-01-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submgr', '0002_alter_subscriptions_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='MonthlyCost',
            field=models.FloatField(),
        ),
    ]
